# Generated by Django 4.2 on 2026-03-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='capacity',
            field=models.PositiveIntegerField(default=3, help_text='Max simultaneous bookings'),
        ),
    ]
