# Generated by Django 6.0 on 2026-03-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='IATA code, e.g. BLR', max_length=10, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance from our facility in km', max_digits=6)),
                ('drive_minutes', models.PositiveIntegerField(help_text='Estimated drive time in minutes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['distance_km'],
            },
        ),
        migrations.CreateModel(
            name='FacilityLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='404 Car Care', max_length=200)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_url', models.URLField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('working_hours', models.JSONField(default=dict, help_text='e.g. {"monday": "8AM-8PM", "sunday": "Closed"}')),
                ('is_primary', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Facility Location',
            },
        ),
    ]
