# Generated by Django 6.0 on 2026-03-07 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hatchback', 'Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV / Crossover'), ('muv', 'MUV / Van'), ('truck', 'Truck / Commercial'), ('luxury', 'Luxury / Premium')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome icon class or emoji', max_length=50)),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
            },
        ),
        migrations.CreateModel(
            name='CeramicCoatingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coating_type', models.CharField(choices=[('1yr', '1 Year Protection'), ('3yr', '3 Year Protection'), ('5yr', '5 Year Protection'), ('ppf', 'Paint Protection Film (PPF)'), ('nano', 'Nano Coating')], max_length=10)),
                ('description', models.TextField()),
                ('includes', models.JSONField(default=list, help_text='List of application steps / what is included')),
                ('warranty_months', models.PositiveIntegerField(default=12)),
                ('gloss_level', models.PositiveIntegerField(default=9, help_text='1-10 gloss rating')),
                ('layers', models.PositiveIntegerField(default=2)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=1, default=4.0, max_digits=4)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceramic_coatings', to='services.servicecategory')),
            ],
            options={
                'ordering': ['coating_type'],
            },
        ),
        migrations.CreateModel(
            name='CarWashService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('wash_type', models.CharField(choices=[('basic', 'Basic Exterior Wash'), ('premium', 'Premium Wash'), ('deluxe', 'Deluxe Wash'), ('interior', 'Interior Cleaning'), ('full', 'Full Service (Exterior + Interior)')], max_length=20)),
                ('description', models.TextField()),
                ('includes', models.JSONField(default=list, help_text='List of included steps')),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wash_services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['wash_type'],
            },
        ),
        migrations.CreateModel(
            name='ServicePricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('car_wash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.carwashservice')),
                ('ceramic_coating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.ceramiccoatingtype')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='services.vehiclecategory')),
            ],
            options={
                'unique_together': {('car_wash', 'vehicle_category'), ('ceramic_coating', 'vehicle_category')},
            },
        ),
    ]
