# Generated by Django 6.0 on 2026-03-07 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('waiting', 'Waiting'), ('preparation', 'Preparation'), ('washing', 'Washing'), ('coating', 'Coating'), ('drying', 'Drying'), ('detailing', 'Detailing'), ('quality_check', 'Quality Check'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('bay_number', models.CharField(blank=True, help_text='e.g. Bay 3', max_length=10)),
                ('is_rush', models.BooleanField(default=False, help_text='Priority job')),
                ('technician_notes', models.TextField(blank=True)),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='jobs/before/')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='jobs/after/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ManyToManyField(blank=True, limit_choices_to={'role': 'staff'}, related_name='assigned_jobs', to=settings.AUTH_USER_MODEL)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_card', to='bookings.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('waiting', 'Waiting'), ('preparation', 'Preparation'), ('washing', 'Washing'), ('coating', 'Coating'), ('drying', 'Drying'), ('detailing', 'Detailing'), ('quality_check', 'Quality Check'), ('completed', 'Completed')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('skipped', 'Skipped')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='jobs/stages/')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_logs', to='monitoring.jobcard')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('started', 'Started Job'), ('stage_update', 'Stage Updated'), ('note_added', 'Note Added'), ('photo_uploaded', 'Photo Uploaded'), ('completed', 'Marked Complete'), ('assigned', 'Staff Assigned')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='monitoring.jobcard')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
